<a href="https://colab.research.google.com/github/Jayaprakash012/Python-Progaramming-Example/blob/main/DissimilarithyMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.spatial.distance import pdist, squareform
data = np.array([
    [1, 2],
    [3,4],
    [5,6]
])
condensed_distance_matrix = pdist(data, metric='euclidean')

dissimilarity_matrix = squareform(condensed_distance_matrix)

print("Dissimilarity Matrix (Euclidean):")
print(dissimilarity_matrix)

Dissimilarity Matrix (Euclidean):
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [ ]:
import numpy as np
from scipy.spatial.distance import pdist, squareform
data = np.array([
    [1, 2],
    [3,4],
    [5,6]
])
condensed_distance_matrix = pdist(data, metric='Jaccard')

dissimilarity_matrix = squareform(condensed_distance_matrix)

print("Dissimilarity Matrix (Jaccard):")
print(dissimilarity_matrix)

Dissimilarity Matrix (Jaccard):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
